### ISSUE TITLE
POST请求怎么把参数加地址上去了

### ISSUE THREAD

**Issue by liangweidonggood** [swxctx/ghttp#5]
param := types.TagCmdQo{
		Id:        666,
		Uid:       "BTT",
		WarnType:  1,
		Display:   1,
		StartTime: 1651219636369,
		Duration:  100,
	}
	req := &ghttp.Request{
		Url:         fmt.Sprintf("%s%s?access_token=%s", baseUrl, types.InstructTheme, GetTokenStr()),
		Method:      "POST",
		Query:       param,
		ContentType: "application/json",
	}
	res, err := req.Do()
	if err != nil {
		log.Println(err)
		return
	}
打印r.Url结果却是
https://xxxxx?display=1&duration=100&id=666&startTime=1651219636369&uid=BTT&warnType=1

**Comment by swxctx** [comment]
req := &ghttp.Request{
Url: fmt.Sprintf("%s%s?access_token=%s", baseUrl, types.InstructTheme, GetTokenStr()),
Method: "POST",
Body: param,
ContentType: "application/json",
}

param参数需要放在body上面，放到Query就到url上面去了
